name: 'Clean & Check'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Markdown
        uses: tomwhross/write-good-action@v1.6
        with:
          directory: ./docs
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.35.0
      name: Spellcheck
      with:
        config_path: .github/spellcheck.yml
        output_file: spellcheck-output.txt
  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: creyD/prettier_action@v4.3
      name: Prettier Action
      with:
        prettier_options: --check *.md
        dry: true
          
