name: 'Deploy'

on:

  workflow_run:
  
    workflows: ["Clean & Check"]
    branches: [main]
    types: 
      - completed

jobs:

  on-success:
  
    runs-on: ubuntu-latest    
    
    env:
      MY_SECRET   : ${{secrets.GH_ACCESS_TOKEN}}
      USER_NAME   : ${{secrets.GH_GIT_USERNAME}}
      USER_EMAIL  : ${{secrets.GH_GIT_EMAIL}}
      BOOK_DIR    : ../docs
      
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    
      - run: echo 'The triggering workflow passed'
      
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        
      - name: Build and Deploy 🚀
        uses: onejar99/gitbook-build-publish-action@v1.0.3
        
  on-failure:
  
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
    
      - run: echo 'The triggering workflow failed'
