name: 'Spellcheck'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: md-spellcheck-action
        uses: matheus23/md-spellcheck-action@v4.2.2
        with:
          # Newline-separated globs of files to check
          files-to-check: /docs
          # A path to a text file with newline-separated custom words to ignore when checking
          #words-to-ignore-file: # optional
                
